<?xml version="1.0" encoding="utf-16"?>

<!DOCTYPE INVENTORY
        [
                <!ELEMENT INVENTORY (BOOK+)>
                <!ELEMENT BOOK (TITLE,AUTHOR,BINDING,PAGES,PRICE)>
                <!ELEMENT TITLE (#PCDATA)>
                <!ELEMENT AUTHOR (#PCDATA)>
                <!ELEMENT BINDING (#PCDATA)>
                <!ELEMENT PAGES (#PCDATA)>
                <!ELEMENT PRICE (#PCDATA)>
         ]>

<INVENTORY>
  <BOOK>
    <TITLE>The Adventures of Huckleberry Finn</TITLE>
    <AUTHOR>Mark Twain</AUTHOR>
    <BINDING>mass market paperback</BINDING>
    <PAGES>298</PAGES>
    <PRICE>$5.49</PRICE>
  </BOOK>
  <BOOK>
    <TITLE>Leaves of Grass</TITLE>
    <AUTHOR>Walt Whitman</AUTHOR>
    <BINDING>hardcover</BINDING>
    <PAGES>462</PAGES>
    <PRICE>$7.75</PRICE>
  </BOOK>
  <BOOK>
    <TITLE>The Legend of Sleepy Hollow</TITLE>
    <AUTHOR>Washington Irving</AUTHOR>
    <BINDING>mass market paperback</BINDING>
    <PAGES>98</PAGES>
    <PRICE>$2.95</PRICE>
  </BOOK>
  <BOOK>
    <TITLE>The Marble Faun</TITLE>
    <AUTHOR>Nathaniel Hawthorne</AUTHOR>
    <BINDING>trade paperback</BINDING>
    <PAGES>473</PAGES>
    <PRICE>$10.95</PRICE>
  </BOOK>
  <BOOK>
    <TITLE>The Portrait of a Lady</TITLE>
    <AUTHOR>Henry James</AUTHOR>
    <BINDING>mass market paperback</BINDING>
    <PAGES>256</PAGES>
    <PRICE>$4.95</PRICE>
  </BOOK>
  <BOOK>
    <TITLE>The Scarlet Letter</TITLE>
    <AUTHOR>Nathaniel Hawthorne</AUTHOR>
    <BINDING>trade paperback</BINDING>
    <PAGES>253</PAGES>
    <PRICE>$4.25</PRICE>
  </BOOK>
  <BOOK>
    <TITLE>The Turn of the Screw</TITLE>
    <AUTHOR>Henry James</AUTHOR>
    <BINDING>trade paperback</BINDING>
    <PAGES>384</PAGES>
    <PRICE>$3.35</PRICE>
  </BOOK>
  <BOOK>
    <TITLE>asdasd</TITLE>
    <AUTHOR>aaaaaaaa</AUTHOR>
    <BINDING>asdasd</BINDING>
    <PAGES>asdsadsa</PAGES>
    <PRICE>asdsdds</PRICE>
  </BOOK>
</INVENTORY>
